---
- name: Ensure needed directories exist
  file:
    path: '{{ item }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
  with_items:
  - '/var/ida-config'
  - '{{ directory_log }}'
  - '{{ directory_data1_root }}/ida'
  - '{{ directory_data1_root }}/log'
  - '{{ directory_data1_root }}/log/audits'
  - '{{ directory_data1_root }}/log/migrations'
  - '{{ directory_data1_root }}/log/rabbitmq_monitoring'
  - '{{ directory_data2_root }}/ida'
  - '{{ directory_data2_root }}/ida_replication'
  - '{{ directory_data2_root }}/ida_trash'
  become: 'yes'
  tags: ida-configure

- name: Link IDA configuration files to source repositories
  file:
    src: '/var/ida-config'
    dest: '{{ item }}'
    state: 'link'
  with_items:
  - '/var/ida/config'
  - '/var/ida/nextcloud/config'
  become: 'yes'
  tags: ida-configure

- name: Ensure IDA config.sh is set correctly
  template:
    src: 'config.sh.j2'
    dest: '/var/ida-config/config.sh'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0666'
  become: 'yes'
  tags: ida-configure
