---
- name: Fetch IDA app repository sources with git
  git:
    repo: '{{ repo_ida_url }}'
    version: '{{ repo_ida_version }}'
    key_file: '{{ deploy_key }}'
    accept_hostkey: 'yes'
    dest: '{{ repo_ida_path }}'
    force: 'yes'
  when: repo_install_method == 'pull'
  tags: ida-repository

- name: Fetch IDA tools repository sources with git
  git:
    repo: '{{ repo_ida_tools_url }}'
    version: '{{ repo_ida_version }}'
    key_file: '{{ deploy_key }}'
    accept_hostkey: 'yes'
    dest: '{{ repo_ida_path }}'
    force: 'yes'
  when: repo_install_method == 'pull'
  tags: ida-repository

- name: Ensure IDA repository is owned by the application user
  file:
    path: '{{ repo_ida_path }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    recurse: 'yes'
  become: yes
  tags: ida-repository
