---
- name: Fetch IDA app repository sources with git
  git:
    repo: '{{ repo_ida_url }}'
    version: '{{ repo_ida_version }}'
    force: 'yes'
    key_file: '{{ deploy_key }}'
    accept_hostkey: 'yes'
    dest: '{{ repo_ida_path }}'
  become: yes
  tags: ida-repository

- name: Ensure repository directory exists with correct permissions
  file:
    path: '{{ repo_ida_path }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    recurse: 'yes'
    state: 'directory'
  become: yes
  tags: ida-repository

# Disabled for now, to enable later
#- name: Fetch IDA tools repository sources with git
#  git:
#    repo: '{{ repo_ida_tools_url }}'
#    version: '{{ repo_ida_tools_version }}'
#    force: 'yes'
#    key_file: '{{ deploy_key }}'
#    accept_hostkey: 'yes'
#    dest: '{{ repo_ida_tools_path }}'
#  tags: ida-repository
