---
- name: Fetch IDA repository sources with git
  git:
    repo: '{{ item.url }}'
    version: '{{ item.version }}'
    force: 'yes'
    key_file: '{{ deploy_key }}'
    accept_hostkey: 'yes'
    dest: '{{ item.dest }}'
  with_items:
  - url: '{{ repo_ida_url }}'
    version: '{{ repo_ida_version }}'
    dest: '{{ repo_ida_path }}'
  - url: '{{ repo_ida_tools_url }}'
    version: '{{ repo_ida_tools_version }}'
    dest: '{{ repo_ida_tools_path }}'
  become: yes
  tags: ida-repository

- name: Ensure IDA repository is owned by the application user
  file:
    path: '{{ repo_ida_path }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
    recurse: 'yes'
  become: yes
  tags: ida-repository
