---
- name: Install IDA Nginx virtual server definition
  template:
    src: 'ida-nginx.conf.j2'
    dest: '/etc/nginx/sites-available/{{ deployment_fqdn }}'
    mode: '0644'
  become: yes
  notify: Restart Nginx
  tags: ida-nginx

- name: Enable IDA Nginx virtual server
  file:
    path: '/etc/nginx/sites-enabled/{{ deployment_fqdn }}'
    src: '/etc/nginx/sites-available/{{ deployment_fqdn }}'
    state: link
  become: yes
  notify: Restart Nginx
  tags: ida-nginx
