---
- name: Ensure that postprocessing virtualenv directory is owned by the application user
  file:
    path: '{{ directory_venv_agents }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    state: 'directory'
  become: yes
  tags: ida-agents

- name: Install IDA agents requirements in virtualenv
  pip:
    requirements: '{{ repo_ida_path }}/requirements.txt'
    virtualenv: '{{ directory_venv_agents }}'
    virtualenv_command: '{{ python_virtualenv_command }}'
  become: yes
  become_user: '{{ application_user }}'
  tags: ida-agents

- name: Ensure IDA agents systemd files are correct
  template:
    src: '{{ item }}.j2'
    dest: '/etc/systemd/system/{{ item }}'
    owner: '{{ application_user }}'
    group: '{{ application_group }}'
    mode: '0644'
  with_items:
    - 'rabbitmq-metadata-agent.service'
    - 'rabbitmq-replication-agent.service'
  become: 'yes'
  tags: ida-agents

- name: Link IDA agents systemd files to agents service files
  file:
    src: '/etc/systemd/system/{{ item }}'
    dest: '/var/ida/agents/services/{{ item }}'
    state: 'link'
  with_items:
  - 'rabbitmq-metadata-agent.service'
  - 'rabbitmq-replication-agent.service'
  become: 'yes'
  tags: ida-agents

- name: Initialize rabbitmq queues for agents
  command:
    cmd: '{{ directory_venv_agents }}/bin/python -m agents.utils.rabbitmq'
    chdir: '{{ repo_ida_path }}'
  become: 'yes'
  notify: Restart IDA agents
  tags: ida-agents

- name: Ensure IDA agents systemd services are started and enabled
  systemd:
    name: '{{ item }}'
    state: 'started'
    enabled: 'yes'
    daemon_reload: 'yes'
  with_items:
    - 'rabbitmq-metadata-agent.service'
    - 'rabbitmq-replication-agent.service'
  become: yes
  tags: ida-agents
