---
- name: Ensure SELinux is disabled
  selinux:
    state: disabled
  become: yes
  when:
    - deploy_application
    - update_proxy
    - update_nginx
    - run_tests
  tags: ida-selinux

- name: Include IDA repository tasks
  include_tasks: "ida-repository.yml"
  when: update_git_repository
  tags: ida-repository

- name: Include IDA configuration tasks
  include_tasks: "ida-configure.yml"
  when: deploy_application
  tags: ida-configure

- name: Include IDA nextcloud tasks
  include_tasks: "ida-nextcloud.yml"
  when: deploy_application
  tags: ida-nextcloud

- name: Include IDA agents tasks
  include_tasks: "ida-agents.yml"
  when: deploy_application
  tags: ida-agents

- name: Include IDA proxy tasks
  include_tasks: "ida-proxy.yml"
  when: update_proxy
  tags: ida-proxy

- name: Include IDA nginx tasks
  include_tasks: "ida-nginx.yml"
  when:
     - update_proxy
     - use_nginx
  tags: ida-nginx

# Delete IDA tests to ensure that they are not run by accident
- name: Delete IDA tests
  file:
    state: absent
    path: '{{ repo_ida_path }}/tests/'
  become: yes
  when: delete_tests
  tags: ida-git-installation

- name: Run IDA tests
  command:
    cmd: '{{ repo_ida_path }}/tests/run-tests'
  become: 'yes'
  when: run_tests
  tags: ida-tests
