---
- name: Restart httpd
  service:
    name: 'httpd'
    state: 'restarted'
  become: yes

- name: Restart Nginx
  systemd:
    name: 'nginx'
    state: 'restarted'
  become: yes

- name: Restart IDA agents
  systemd:
    name: '{{ item }}'
    state: 'restarted'
  with_items:
    - 'fairdata-ida-metadata-agent.service'
    - 'fairdata-ida-replication-agent.service'
  become: yes
